# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mm8013c_fg_mmi

EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/include \
		        -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/drivers/power/supply

obj-m += mm8013c_battery.o
