ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-6.6/include \
		-I$(ANDROID_BUILD_TOP)/kernel-6.6/include/linux/power \
                -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/include \
		-I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.6/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/cps4038


obj-m += cps_wls_charger_4038.o
cps_wls_charger_4038-objs += moto_wls_auth2.0.o
cps_wls_charger_4038-objs += cps_wls_charger.o
