ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

EXTRA_CFLAGS += -I$(PWD)
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_device_modules-6.1/drivers/power/supply
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include


obj-m += moto_wlc2_alg.o
moto_wlc2_alg-objs := moto_wlc2.o moto_wlc2_hal.o moto_wlc2_chg.o moto_wlc2_device.o moto_wlc2_config.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../power/mmi_wireless_class/$(GKI_OBJ_MODULE_DIR)/Module.symvers
