# add -Wall to try to catch everything we can.
ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-m        += tms_nfc.o
tms_nfc-objs:= ese_common.o ese_driver.o guide_driver.o nfc_common.o nfc_driver.o tms_common.o

#KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/Module.symvers
