# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \

goodix_fod_mmi_u-y += gf_fod_tee.o

obj-m += goodix_fod_mmi_u.o

